# Compile the firmware-signing public key into the image.
#
# With a public key found (firmware_signing.public_key_path:
# CALLIOPE_FIRMWARE_PUBKEY, else ~/.config/calliope/firmware-signing.pub.pem
# beside the private key, else keys/firmware-signing.pub.pem), the build
# defines FIRMWARE_SIGNING and the satellite refuses every over-the-air image
# that is not signed by the matching private key. Without one the build still
# succeeds, prints a warning nobody can miss, and the satellite accepts
# unsigned images: that is a development build, and it must not reach a
# satellite that anyone else relies on.
#
# The repository carries no key, so a fresh clone builds unsigned until its
# owner makes a key pair of their own (keys/README.md).
import os
import sys

Import("env")  # noqa: F821  (PlatformIO injects it)

project = env.subst("$PROJECT_DIR")  # noqa: F821
sys.path.insert(0, os.path.join(project, "scripts"))  # SCons scripts have no __file__
import firmware_signing  # noqa: E402

pub_path = firmware_signing.public_key_path(project)
out_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
os.makedirs(out_dir, exist_ok=True)
header = os.path.join(out_dir, "firmware_key.h")

if pub_path and not os.path.exists(pub_path):
    # Named on purpose and missing: an unsigned build here would be a typo
    # away from a satellite that accepts anything.
    sys.exit(f"{firmware_signing.PUBLIC_KEY_ENV}={pub_path}: no such file")
if pub_path:
    with open(pub_path) as f:
        pem = f.read()
    try:
        der = firmware_signing.pem_to_der(pem)
        firmware_signing.check_p256_public_key(der)
    except ValueError as e:
        # A build with an unusable key would refuse every future update,
        # including the one that fixes it. Stop here instead.
        sys.exit(f"{pub_path}: {e}")
    kid = firmware_signing.key_id(der)
    body = ", ".join(f"0x{b:02x}" for b in der)
    text = (
        "// Generated by scripts/firmware_key.py from "
        f"{os.path.basename(pub_path)}. Do not edit.\n"
        "#pragma once\n"
        f'#define FIRMWARE_KEY_ID "{kid}"\n'
        f"static const unsigned char FIRMWARE_KEY_DER[{len(der)}] = {{{body}}};\n"
    )
    env.Append(CPPDEFINES=["FIRMWARE_SIGNING"])  # noqa: F821
    print(f"firmware signing: updates must be signed by key {kid} ({pub_path})")
else:
    text = "// Generated by scripts/firmware_key.py: no signing key, updates are unsigned.\n#pragma once\n"
    bar = "!" * 78
    places = "\n".join(f"    {p}" for p in firmware_signing.public_key_places(project))
    print(f"\n{bar}\n"
          f"  UNSIGNED BUILD: {firmware_signing.PUBLIC_KEY_ENV} is not set, and there is no\n"
          "  firmware signing public key at\n"
          f"{places}\n"
          "  so this image accepts ANY over-the-air update the hub sends it.\n"
          "  Fine on a bench; not on a satellite anyone relies on.\n"
          "  keys/README.md says how to make the key pair.\n"
          f"{bar}\n", file=sys.stderr)

# Rewrite only on change, so an unchanged key does not force a rebuild.
old = open(header).read() if os.path.exists(header) else None
if old != text:
    with open(header, "w") as f:
        f.write(text)
env.Append(CPPPATH=[out_dir])  # noqa: F821
