# Compile the certificates a release build trusts for its wss:// hub into the
# image, as CA_BUNDLE (src/hub.cpp, ws.beginSslWithCA).
#
# The satellite checks the hub's certificate chain and host name against these
# and nothing else. A hub whose certificate chains to any other CA fails the
# TLS handshake, and the satellite stays in Connecting with nothing to say why.
#
# CALLIOPE_HUB_CA names a PEM file of one or more CA certificates to trust
# instead: a private CA, Caddy's internal one, a self-signed certificate, or
# the root of whichever public CA signs the gateway's certificate (ZeroSSL,
# Google Trust Services...). To trust Let's Encrypt as well, put both in one
# file. Unset, the build trusts certs/lets-encrypt-roots.pem, ISRG Root X1 and
# X2. Each certificate is parsed into the heap at every connect, so the file
# holds the roots the hub needs, not a whole system bundle.
import base64
import binascii
import os
import re
import sys

Import("env")  # noqa: F821  (PlatformIO injects it)

project = env.subst("$PROJECT_DIR")  # noqa: F821
named = os.environ.get("CALLIOPE_HUB_CA")
path = os.path.expanduser(named) if named else os.path.join(project, "certs", "lets-encrypt-roots.pem")
where = f"CALLIOPE_HUB_CA={path}" if named else path

try:
    with open(path) as f:
        text = f.read()
except OSError as e:
    sys.exit(f"{where}: {e.strerror}")

certs = []
for body in re.findall(r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", text, re.S):
    b64 = "".join(body.split())
    try:
        der = base64.b64decode(b64, validate=True)
    except binascii.Error:
        der = b""
    if not der.startswith(b"\x30"):  # a certificate is a DER SEQUENCE
        sys.exit(f"{where}: a CERTIFICATE block that is not a certificate")
    certs.append(b64)
if not certs:
    # A build that trusts nothing could never reach its hub, and the satellite
    # would say no more than that it is connecting.
    sys.exit(f"{where}: no PEM certificate in it (a '-----BEGIN CERTIFICATE-----' block)")

lines = []
for b64 in certs:
    lines += ["-----BEGIN CERTIFICATE-----",
              *(b64[i:i + 64] for i in range(0, len(b64), 64)),
              "-----END CERTIFICATE-----"]
text = (
    f"// Generated by scripts/hub_ca.py from {os.path.basename(path)}. Do not edit.\n"
    "#pragma once\n"
    "static const char CA_BUNDLE[] =\n"
    + "".join(f'    "{line}\\n"\n' for line in lines)
    + "    ;\n"
)
print(f"hub TLS: trusts {len(certs)} CA certificate(s) from {path}")

out_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
os.makedirs(out_dir, exist_ok=True)
header = os.path.join(out_dir, "hub_ca.h")
# Rewrite only on change, so unchanged roots do not force a rebuild.
old = open(header).read() if os.path.exists(header) else None
if old != text:
    with open(header, "w") as f:
        f.write(text)
env.Append(CPPPATH=[out_dir])  # noqa: F821
