"""Two thin pydantic bases, and no more.

`Segment` is declared twice today, in tts-stack/app/main.py and
tts-long/app/main.py, with identical bounds. Identical bounds that nobody is
checking: 0.0 to 10.0 seconds of pause is a documented part of both APIs, and
a drift in either direction is a silent change to a published contract.

`OpenAISpeechRequest` carries one rule that is easy to lose. tts-stack reasoned
it out explicitly — a service whose whole purpose is answering OpenAI's clients
must not reject one for sending `instructions` or `stream_format`, because
OpenAI keeps adding fields and the client speaking a newer dialect is not the
client's fault. tts-long gets the same behaviour only because it never said
`extra="forbid"`, which is luck rather than a decision. Putting `extra="allow"`
in the base means the next /v1 route inherits the reasoning instead of
rediscovering it.

Note the two configs point opposite ways, and both are right: `Segment` is
part of the NATIVE API, where a typo in a field name should be a 422 rather
than silently ignored audio; `OpenAISpeechRequest` is part of a COMPATIBILITY
surface, where strictness is a bug.

**This is the module most at risk of growing.** Everything that actually
differs stays subclassed per service: the format enum, the speed range —
tts-stack clamps OpenAI's 0.25–4.0 into Kokoro's 0.5–2.0 because a client
cannot be told to send something else, while tts-long refuses any speed but
1.0 because Chatterbox has no rate control and resampling would shift pitch —
and every vendor extra. If a third field looks like it belongs here, that is
probably the boundary being wrong rather than the module being incomplete.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

__all__ = ["Segment", "OpenAISpeechRequest"]


class Segment(BaseModel):
    """One piece of text and the silence that follows it.

    The pause is generated by the caller, not asked of the model: no TTS model
    reliably produces a beat you can act inside. Punctuation buys a breath; an
    instruction needs a gap.

    Unknown fields are rejected rather than dropped. tts-stack documented a
    per-segment `voice` for as long as it was silently ignored, and the caller
    got the default voice back with nothing to read that said why. A typo
    belongs in a 422, not in the audio.
    """

    model_config = ConfigDict(extra="forbid")

    text: str
    # 10 seconds is not a technical limit; it is the point past which a pause
    # is a separate request. Both services publish this range already.
    pause_after: float = Field(default=0.0, ge=0.0, le=10.0)


class OpenAISpeechRequest(BaseModel):
    """The fields OpenAI's /v1/audio/speech body shares across these services.

    `model` is accepted and ignored: there is one model per service, and
    rejecting "tts-1" would break every client that sends it while claiming to
    honour it would be a lie.

    `voice` is optional, unlike upstream, because every service here has an
    answer when the field is absent: tts-stack falls back to TTS_VOICE, and
    tts-long to Chatterbox's own built-in speaker, which is the one voice that
    is always present whether or not any reference clip is installed.

    `response_format` is NOT here. The enum is a property of the image, not of
    the wire, and the two services do not even decide it the same way:
    tts-stack fixes it at import as a Literal over the formats it ships, while
    tts-long computes it at start-up from whether ffmpeg is on PATH, so the
    same code answers three formats or six depending on the image it is in.
    Subclass and declare what that image can actually produce.
    """

    # extra="allow", and this is the point of the class. See the module
    # docstring: OpenAI adds fields, and a compatibility layer that 422s on
    # `instructions` is broken by its own strictness.
    model_config = ConfigDict(extra="allow")

    model: str = "default"
    input: str
    voice: str | None = None
    speed: float = 1.0
